### PR TITLE
New RFC: Appwrite CLI

### PR DESCRIPTION
**Pull request by eldadfux**
Attached RFC #4

### CODE REVIEW

**Comment by TorstenDittmann** [comment]
I'm not sure if the PHP approach is the best here, especially due to the dependency on Docker.  Because the CLI is most likely also used in CI/CD, we should keep the runtime as optimal as possible.  For example, Node.js (soon also Deno) has many libraries and resources that allow such a CLI to be generated quite efficiently. It can also be bundled with tools like `pkg` to remove any dependencies at all and supports every major platform.

**Comment by eldadfux** [comment]
The packaging with Docker is designed to comply with our vision of cross-platform / tech agnostic platform. It allows us to have one language-agnostic tool, with minimum requirements to start working with the CLI, and also takes into account that Docker is an already exciting Appwrite dependency. The usage of PHP is obviously leveraging our already in-use tools stack.

Besides the above, Docker also offers our devs easy installation (no pip/npm/brew package manager needed), no language-specific version requirement or incompatibility with older langs, and extra security to the user, as our CLI has no unauthorized access to user operating system.

**Comment by TorstenDittmann** [comment]
Okay, fair and understandable points.  Yesterday I also read an article on the subject which resolved some of my concerns, and I sometimes forget how Docker performs - also in CI / CD.

**Comment by TorstenDittmann** [comment]
For removing the prefix, the only thing that comes to my mind is adding an `Alias` to the shell/term.

**Comment by christyjacob4** [comment]
Looks good @eldadfux  . Shall I go ahead with the implementation? Regarding the Alias, we'll figure out something along the way 👍

**Review by christyjacob4 — APPROVED** [review]

**Comment by eldadfux** [comment]
> Looks good @eldadfux . Shall I go ahead with the implementation? Regarding the Alias, we'll figure out something along the way 👍

100%

**Pull request merged**
